//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecGroupSisVentasFrondEnd2021.ServicioProducto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/TecGroup.Dominio.Entidades")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DestacadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrecioCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrecioVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadMedidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescProducto {
            get {
                return this.DescProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescProductoField, value) != true)) {
                    this.DescProductoField = value;
                    this.RaisePropertyChanged("DescProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Destacado {
            get {
                return this.DestacadoField;
            }
            set {
                if ((this.DestacadoField.Equals(value) != true)) {
                    this.DestacadoField = value;
                    this.RaisePropertyChanged("Destacado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstadoProducto {
            get {
                return this.EstadoProductoField;
            }
            set {
                if ((this.EstadoProductoField.Equals(value) != true)) {
                    this.EstadoProductoField = value;
                    this.RaisePropertyChanged("EstadoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria {
            get {
                return this.IdCategoriaField;
            }
            set {
                if ((this.IdCategoriaField.Equals(value) != true)) {
                    this.IdCategoriaField = value;
                    this.RaisePropertyChanged("IdCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProducto {
            get {
                return this.NombreProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreProductoField, value) != true)) {
                    this.NombreProductoField = value;
                    this.RaisePropertyChanged("NombreProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PrecioCompra {
            get {
                return this.PrecioCompraField;
            }
            set {
                if ((this.PrecioCompraField.Equals(value) != true)) {
                    this.PrecioCompraField = value;
                    this.RaisePropertyChanged("PrecioCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PrecioVenta {
            get {
                return this.PrecioVentaField;
            }
            set {
                if ((this.PrecioVentaField.Equals(value) != true)) {
                    this.PrecioVentaField = value;
                    this.RaisePropertyChanged("PrecioVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadMedida {
            get {
                return this.UnidadMedidaField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadMedidaField, value) != true)) {
                    this.UnidadMedidaField = value;
                    this.RaisePropertyChanged("UnidadMedida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioProducto.IProductoRestServicio")]
    public interface IProductoRestServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoRestServicio/ObtenerporId", ReplyAction="http://tempuri.org/IProductoRestServicio/ObtenerporIdResponse")]
        TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto ObtenerporId(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoRestServicio/ObtenerporId", ReplyAction="http://tempuri.org/IProductoRestServicio/ObtenerporIdResponse")]
        System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto> ObtenerporIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoRestServicio/Listado", ReplyAction="http://tempuri.org/IProductoRestServicio/ListadoResponse")]
        TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto[] Listado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoRestServicio/Listado", ReplyAction="http://tempuri.org/IProductoRestServicio/ListadoResponse")]
        System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto[]> ListadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoRestServicio/Insertar", ReplyAction="http://tempuri.org/IProductoRestServicio/InsertarResponse")]
        int Insertar(TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoRestServicio/Insertar", ReplyAction="http://tempuri.org/IProductoRestServicio/InsertarResponse")]
        System.Threading.Tasks.Task<int> InsertarAsync(TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoRestServicio/Eliminar", ReplyAction="http://tempuri.org/IProductoRestServicio/EliminarResponse")]
        int Eliminar(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoRestServicio/Eliminar", ReplyAction="http://tempuri.org/IProductoRestServicio/EliminarResponse")]
        System.Threading.Tasks.Task<int> EliminarAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoRestServicio/Actualizar", ReplyAction="http://tempuri.org/IProductoRestServicio/ActualizarResponse")]
        int Actualizar(TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoRestServicio/Actualizar", ReplyAction="http://tempuri.org/IProductoRestServicio/ActualizarResponse")]
        System.Threading.Tasks.Task<int> ActualizarAsync(TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoRestServicio/Anular", ReplyAction="http://tempuri.org/IProductoRestServicio/AnularResponse")]
        int Anular(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoRestServicio/Anular", ReplyAction="http://tempuri.org/IProductoRestServicio/AnularResponse")]
        System.Threading.Tasks.Task<int> AnularAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoRestServicio/ObtenerporNombre", ReplyAction="http://tempuri.org/IProductoRestServicio/ObtenerporNombreResponse")]
        TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto[] ObtenerporNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoRestServicio/ObtenerporNombre", ReplyAction="http://tempuri.org/IProductoRestServicio/ObtenerporNombreResponse")]
        System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto[]> ObtenerporNombreAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductoRestServicioChannel : TecGroupSisVentasFrondEnd2021.ServicioProducto.IProductoRestServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoRestServicioClient : System.ServiceModel.ClientBase<TecGroupSisVentasFrondEnd2021.ServicioProducto.IProductoRestServicio>, TecGroupSisVentasFrondEnd2021.ServicioProducto.IProductoRestServicio {
        
        public ProductoRestServicioClient() {
        }
        
        public ProductoRestServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoRestServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoRestServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoRestServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto ObtenerporId(string id) {
            return base.Channel.ObtenerporId(id);
        }
        
        public System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto> ObtenerporIdAsync(string id) {
            return base.Channel.ObtenerporIdAsync(id);
        }
        
        public TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto[] Listado() {
            return base.Channel.Listado();
        }
        
        public System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto[]> ListadoAsync() {
            return base.Channel.ListadoAsync();
        }
        
        public int Insertar(TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto producto) {
            return base.Channel.Insertar(producto);
        }
        
        public System.Threading.Tasks.Task<int> InsertarAsync(TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto producto) {
            return base.Channel.InsertarAsync(producto);
        }
        
        public int Eliminar(string id) {
            return base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task<int> EliminarAsync(string id) {
            return base.Channel.EliminarAsync(id);
        }
        
        public int Actualizar(TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto producto) {
            return base.Channel.Actualizar(producto);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarAsync(TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto producto) {
            return base.Channel.ActualizarAsync(producto);
        }
        
        public int Anular(string id) {
            return base.Channel.Anular(id);
        }
        
        public System.Threading.Tasks.Task<int> AnularAsync(string id) {
            return base.Channel.AnularAsync(id);
        }
        
        public TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto[] ObtenerporNombre(string nombre) {
            return base.Channel.ObtenerporNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioProducto.Producto[]> ObtenerporNombreAsync(string nombre) {
            return base.Channel.ObtenerporNombreAsync(nombre);
        }
    }
}
