//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecGroupSisVentasFrondEnd2021.ServicioCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/TecGroup.Dominio.Entidades")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EstadoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SaldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idDistritoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EstadoCliente {
            get {
                return this.EstadoClienteField;
            }
            set {
                if ((this.EstadoClienteField.Equals(value) != true)) {
                    this.EstadoClienteField = value;
                    this.RaisePropertyChanged("EstadoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomDistrito {
            get {
                return this.NomDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomDistritoField, value) != true)) {
                    this.NomDistritoField = value;
                    this.RaisePropertyChanged("NomDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idDistrito {
            get {
                return this.idDistritoField;
            }
            set {
                if ((this.idDistritoField.Equals(value) != true)) {
                    this.idDistritoField = value;
                    this.RaisePropertyChanged("idDistrito");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCliente.IClienteRestServicio")]
    public interface IClienteRestServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRestServicio/ObtenerporId", ReplyAction="http://tempuri.org/IClienteRestServicio/ObtenerporIdResponse")]
        TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente ObtenerporId(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRestServicio/ObtenerporId", ReplyAction="http://tempuri.org/IClienteRestServicio/ObtenerporIdResponse")]
        System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente> ObtenerporIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRestServicio/Listado", ReplyAction="http://tempuri.org/IClienteRestServicio/ListadoResponse")]
        TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente[] Listado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRestServicio/Listado", ReplyAction="http://tempuri.org/IClienteRestServicio/ListadoResponse")]
        System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente[]> ListadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRestServicio/Insertar", ReplyAction="http://tempuri.org/IClienteRestServicio/InsertarResponse")]
        int Insertar(TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRestServicio/Insertar", ReplyAction="http://tempuri.org/IClienteRestServicio/InsertarResponse")]
        System.Threading.Tasks.Task<int> InsertarAsync(TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRestServicio/Eliminar", ReplyAction="http://tempuri.org/IClienteRestServicio/EliminarResponse")]
        int Eliminar(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRestServicio/Eliminar", ReplyAction="http://tempuri.org/IClienteRestServicio/EliminarResponse")]
        System.Threading.Tasks.Task<int> EliminarAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRestServicio/Actualizar", ReplyAction="http://tempuri.org/IClienteRestServicio/ActualizarResponse")]
        int Actualizar(TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRestServicio/Actualizar", ReplyAction="http://tempuri.org/IClienteRestServicio/ActualizarResponse")]
        System.Threading.Tasks.Task<int> ActualizarAsync(TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRestServicio/Anular", ReplyAction="http://tempuri.org/IClienteRestServicio/AnularResponse")]
        int Anular(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRestServicio/Anular", ReplyAction="http://tempuri.org/IClienteRestServicio/AnularResponse")]
        System.Threading.Tasks.Task<int> AnularAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRestServicio/ObtenerporNombre", ReplyAction="http://tempuri.org/IClienteRestServicio/ObtenerporNombreResponse")]
        TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente[] ObtenerporNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRestServicio/ObtenerporNombre", ReplyAction="http://tempuri.org/IClienteRestServicio/ObtenerporNombreResponse")]
        System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente[]> ObtenerporNombreAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteRestServicioChannel : TecGroupSisVentasFrondEnd2021.ServicioCliente.IClienteRestServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteRestServicioClient : System.ServiceModel.ClientBase<TecGroupSisVentasFrondEnd2021.ServicioCliente.IClienteRestServicio>, TecGroupSisVentasFrondEnd2021.ServicioCliente.IClienteRestServicio {
        
        public ClienteRestServicioClient() {
        }
        
        public ClienteRestServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteRestServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteRestServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteRestServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente ObtenerporId(string id) {
            return base.Channel.ObtenerporId(id);
        }
        
        public System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente> ObtenerporIdAsync(string id) {
            return base.Channel.ObtenerporIdAsync(id);
        }
        
        public TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente[] Listado() {
            return base.Channel.Listado();
        }
        
        public System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente[]> ListadoAsync() {
            return base.Channel.ListadoAsync();
        }
        
        public int Insertar(TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente cliente) {
            return base.Channel.Insertar(cliente);
        }
        
        public System.Threading.Tasks.Task<int> InsertarAsync(TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente cliente) {
            return base.Channel.InsertarAsync(cliente);
        }
        
        public int Eliminar(string id) {
            return base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task<int> EliminarAsync(string id) {
            return base.Channel.EliminarAsync(id);
        }
        
        public int Actualizar(TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente cliente) {
            return base.Channel.Actualizar(cliente);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarAsync(TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente cliente) {
            return base.Channel.ActualizarAsync(cliente);
        }
        
        public int Anular(string id) {
            return base.Channel.Anular(id);
        }
        
        public System.Threading.Tasks.Task<int> AnularAsync(string id) {
            return base.Channel.AnularAsync(id);
        }
        
        public TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente[] ObtenerporNombre(string nombre) {
            return base.Channel.ObtenerporNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioCliente.Cliente[]> ObtenerporNombreAsync(string nombre) {
            return base.Channel.ObtenerporNombreAsync(nombre);
        }
    }
}
