//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecGroupSisVentasFrondEnd2021.ServicioUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/TecGroup.Dominio.Entidades")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EstadoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SaldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UltimaConexionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idDistritoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EstadoCliente {
            get {
                return this.EstadoClienteField;
            }
            set {
                if ((this.EstadoClienteField.Equals(value) != true)) {
                    this.EstadoClienteField = value;
                    this.RaisePropertyChanged("EstadoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomDistrito {
            get {
                return this.NomDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomDistritoField, value) != true)) {
                    this.NomDistritoField = value;
                    this.RaisePropertyChanged("NomDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUsuarioField, value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UltimaConexion {
            get {
                return this.UltimaConexionField;
            }
            set {
                if ((this.UltimaConexionField.Equals(value) != true)) {
                    this.UltimaConexionField = value;
                    this.RaisePropertyChanged("UltimaConexion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idDistrito {
            get {
                return this.idDistritoField;
            }
            set {
                if ((this.idDistritoField.Equals(value) != true)) {
                    this.idDistritoField = value;
                    this.RaisePropertyChanged("idDistrito");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioUsuario.IUsuarioRestServicio")]
    public interface IUsuarioRestServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioRestServicio/ObtenerporId", ReplyAction="http://tempuri.org/IUsuarioRestServicio/ObtenerporIdResponse")]
        TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario ObtenerporId(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioRestServicio/ObtenerporId", ReplyAction="http://tempuri.org/IUsuarioRestServicio/ObtenerporIdResponse")]
        System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario> ObtenerporIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioRestServicio/Listado", ReplyAction="http://tempuri.org/IUsuarioRestServicio/ListadoResponse")]
        TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario[] Listado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioRestServicio/Listado", ReplyAction="http://tempuri.org/IUsuarioRestServicio/ListadoResponse")]
        System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario[]> ListadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioRestServicio/Insertar", ReplyAction="http://tempuri.org/IUsuarioRestServicio/InsertarResponse")]
        int Insertar(TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioRestServicio/Insertar", ReplyAction="http://tempuri.org/IUsuarioRestServicio/InsertarResponse")]
        System.Threading.Tasks.Task<int> InsertarAsync(TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioRestServicio/Eliminar", ReplyAction="http://tempuri.org/IUsuarioRestServicio/EliminarResponse")]
        int Eliminar(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioRestServicio/Eliminar", ReplyAction="http://tempuri.org/IUsuarioRestServicio/EliminarResponse")]
        System.Threading.Tasks.Task<int> EliminarAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioRestServicio/Actualizar", ReplyAction="http://tempuri.org/IUsuarioRestServicio/ActualizarResponse")]
        int Actualizar(TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioRestServicio/Actualizar", ReplyAction="http://tempuri.org/IUsuarioRestServicio/ActualizarResponse")]
        System.Threading.Tasks.Task<int> ActualizarAsync(TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioRestServicio/Anular", ReplyAction="http://tempuri.org/IUsuarioRestServicio/AnularResponse")]
        int Anular(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioRestServicio/Anular", ReplyAction="http://tempuri.org/IUsuarioRestServicio/AnularResponse")]
        System.Threading.Tasks.Task<int> AnularAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioRestServicio/ObtenerporNombre", ReplyAction="http://tempuri.org/IUsuarioRestServicio/ObtenerporNombreResponse")]
        TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario[] ObtenerporNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioRestServicio/ObtenerporNombre", ReplyAction="http://tempuri.org/IUsuarioRestServicio/ObtenerporNombreResponse")]
        System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario[]> ObtenerporNombreAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioRestServicioChannel : TecGroupSisVentasFrondEnd2021.ServicioUsuario.IUsuarioRestServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioRestServicioClient : System.ServiceModel.ClientBase<TecGroupSisVentasFrondEnd2021.ServicioUsuario.IUsuarioRestServicio>, TecGroupSisVentasFrondEnd2021.ServicioUsuario.IUsuarioRestServicio {
        
        public UsuarioRestServicioClient() {
        }
        
        public UsuarioRestServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioRestServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioRestServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioRestServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario ObtenerporId(string id) {
            return base.Channel.ObtenerporId(id);
        }
        
        public System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario> ObtenerporIdAsync(string id) {
            return base.Channel.ObtenerporIdAsync(id);
        }
        
        public TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario[] Listado() {
            return base.Channel.Listado();
        }
        
        public System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario[]> ListadoAsync() {
            return base.Channel.ListadoAsync();
        }
        
        public int Insertar(TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario Usuario) {
            return base.Channel.Insertar(Usuario);
        }
        
        public System.Threading.Tasks.Task<int> InsertarAsync(TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario Usuario) {
            return base.Channel.InsertarAsync(Usuario);
        }
        
        public int Eliminar(string id) {
            return base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task<int> EliminarAsync(string id) {
            return base.Channel.EliminarAsync(id);
        }
        
        public int Actualizar(TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario Usuario) {
            return base.Channel.Actualizar(Usuario);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarAsync(TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario Usuario) {
            return base.Channel.ActualizarAsync(Usuario);
        }
        
        public int Anular(string id) {
            return base.Channel.Anular(id);
        }
        
        public System.Threading.Tasks.Task<int> AnularAsync(string id) {
            return base.Channel.AnularAsync(id);
        }
        
        public TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario[] ObtenerporNombre(string nombre) {
            return base.Channel.ObtenerporNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<TecGroupSisVentasFrondEnd2021.ServicioUsuario.Usuario[]> ObtenerporNombreAsync(string nombre) {
            return base.Channel.ObtenerporNombreAsync(nombre);
        }
    }
}
